Feature/index questionnaire answers
Platoniq/decidim pull request #15
Opened 2020-01-20 14:40 UTC by verarojman

#### :tophat: What? Why?

#### :pushpin: Related Issues
- Related to #?
- Fixes #?

#### :clipboard: Subtasks
- [x] Add `CHANGELOG` entry
- [ ] Add documentation regarding the feature 
- [ ] Add/modify seeds
- [ ] Add tests
- [ ] Another subtask

### :camera: Screenshots (optional)
![Description](URL)

2020-01-22 15:58 UTC, microstudi requested changes
Aixo pinta molt bé, felicitats!
un parell de cosetes t'he comentat.
Aquests dies acabaré de provar-ho també

2020-01-22 15:58 UTC, microstudi commented on decidim-forms/app/controllers/decidim/forms/admin/concerns/has_questionnaire_answers.rb
> +        # returns an instance of the model that questionnaire belongs to.
Aquest text hauria de ser actualizat amb el propósit d'aquest mòdul en concret

2020-01-22 15:58 UTC, microstudi commented on decidim-forms/app/controllers/decidim/forms/admin/concerns/has_questionnaire_answers.rb
> +            helper_method :questionnaire_url, :questionnaire_participants_url, :questionnaire_participant_answers_url, :questionnaire_export_url, :questionnaire_export_response_url
Hauriem d'extreure els helpers a una classe a part per fer una mica més agradable aquesta

2020-01-22 15:58 UTC, microstudi commented on decidim-forms/app/queries/decidim/forms/questionnaire_participants.rb
> +              .select(:session_token, :decidim_user_id, :ip_hash).distinct
crec que ip_hash aqui sobra, de fet només s'ha de distingir per :session_token

2020-01-23 17:03 UTC, verarojman commented on decidim-forms/app/controllers/decidim/forms/admin/concerns/has_questionnaire_answers.rb
> +        # returns an instance of the model that questionnaire belongs to.
Fet! Si creus que falta alguna cosa diga'm i ho afegeixo :)

2020-01-23 17:20 UTC, verarojman commented on decidim-forms/app/queries/decidim/forms/questionnaire_participants.rb
> +              .select(:session_token, :decidim_user_id, :ip_hash).distinct
Això era per simplificar la inclusió d'aquests camps a la query que agrupa les respostes per participant, ja que sinó s'ha de fer servir el de la primera resposta de l'usuari. Si tot i així et sembla millor canviar-ho, diga-m'ho i ho refactoritzo.

2020-01-23 17:29 UTC, verarojman commented on decidim-forms/app/controllers/decidim/forms/admin/concerns/has_questionnaire_answers.rb
> +            helper_method :questionnaire_url, :questionnaire_participants_url, :questionnaire_participant_answers_url, :questionnaire_export_url, :questionnaire_export_response_url
Fet!

2020-01-24 11:04 UTC, microstudi requested changes
Ok, almost done. Un parell de comentaris i ja estarà

2020-01-24 11:04 UTC, microstudi commented on decidim-forms/app/queries/decidim/forms/questionnaire_participants.rb
> +              .select(:session_token, :decidim_user_id, :ip_hash).distinct
ah ok. Potser comentar-ho. De totes maneres no es podria reaprofitar la query QuestionnaireParticipant? per repetir menys codi

2020-01-24 11:04 UTC, microstudi commented on decidim-forms/app/controllers/decidim/forms/admin/concerns/has_questionnaire_answers.rb
> +            helper_method :questionnaire_url, :questionnaire_participants_url,
```suggestion
```
Això ja es innecessari oi?

2020-01-24 11:04 UTC, microstudi commented on decidim-forms/app/controllers/decidim/forms/admin/concerns/has_questionnaire_answers.rb
> +            helper Decidim::Forms::Admin::QuestionnaireAnswersHelper
Aquest 2 no fan la mateixsa funció? helper a un sol lloc, o 2 si queda molt llarg separat per funció (per exemple paginació i presentació)

2020-01-24 11:04 UTC, microstudi commented on decidim-forms/spec/presenters/decidim/admin/questionnaire_participant_presenter_spec.rb
> +        if answer.ip_hash.present?
Aquest test no diu molta cosa, si `ip_hash` no està present simplement mai s'executarà.
Potser millor fer 2 casos amb `context` i fer alguna cosa com:
```ruby
describe "ip_hash"
  context "when participant's ip_hash is present" do
    before do 
      answer.ip_hash = "some ip"
    end
    it "returns participant ip hash"
      expect(subject.ip_hash).to eq(answer.ip_hash)
    end
  end
    context "when participant's ip_hash is missing do
...
end
```

2020-01-24 11:04 UTC, microstudi commented on decidim-forms/app/controllers/decidim/forms/admin/concerns/has_questionnaire_answers.rb
> +        # returns an instance of the model that questionnaire belongs to.
nice!

2020-01-24 16:33 UTC, verarojman commented on decidim-forms/spec/presenters/decidim/admin/questionnaire_participant_presenter_spec.rb
> +        if answer.ip_hash.present?
Fet!

2020-01-24 16:34 UTC, verarojman commented on decidim-forms/app/controllers/decidim/forms/admin/concerns/has_questionnaire_answers.rb
> +            helper_method :questionnaire_url, :questionnaire_participants_url,
He fet un refactor separant els helpers en dos fitxers a part, diga'm si et sembla correcte.

2020-01-24 16:37 UTC, verarojman commented on decidim-forms/app/queries/decidim/forms/questionnaire_participants.rb
> +              .select(:session_token, :decidim_user_id, :ip_hash).distinct
Idealment QuestionnaireParticipant hauria de ser un model i això simplificaria moltíssim tot plegat. Ho hauria d'haver fet així des del principi, potser podem mirar-ho junts el dilluns i evaluar si creem aquest model o ho deixem així.

2020-02-21 10:20 UTC, microstudi approved these changes

2020-02-21 10:20 UTC, microstudi commented on decidim-core/lib/decidim/exporters/pdf.rb
> +    # the columns: [TODO!]
ojo aquest TODO!

2020-02-21 10:31 UTC, merged