change
Platoniq/decidim pull request #33
Opened 2020-11-13 09:42 UTC by IvanOrtizp

#### :tophat: What? Why?
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #?
- Fixes #?

#### Testing
*Describe the best way to test or validate your PR.*

#### :clipboard: Checklist
:rotating_light: Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] :question: **CONSIDER** adding a unit test if your PR resolves an issue.
- [ ] :heavy_check_mark: **DO** check open PR's to avoid duplicates.
- [ ] :heavy_check_mark: **DO** keep pull requests small so they can be easily reviewed.
- [ ] :heavy_check_mark: **DO** build locally before pushing.
- [ ] :heavy_check_mark: **DO** make sure tests pass.
- [ ] :heavy_check_mark: **DO** make sure any new changes are documented in `docs/`.
- [ ] :heavy_check_mark: **DO** add and modify seeds if necessary.
- [ ] :heavy_check_mark: **DO** add CHANGELOG upgrade notes if required.
- [ ] :heavy_check_mark: **DO** add to GraphQL API if there are new public fields.
- [ ] :heavy_check_mark: **DO** add link to MetaDecidim if it's a new feature.
- [ ] :x:**AVOID** breaking the continuous integration build.
- [ ] :x:**AVOID** making significant changes to the overall architecture.

### :camera: Screenshots
*Please add screenshots of the changes you're proposing*
![Description](URL)

:hearts: Thank you!

2020-11-26 10:37 UTC, microstudi requested changes
primer exemple de review (les reals son en anglès):

- [ ] Falta millorar la descripció del que has fet, no cal posar "I fix", es millor posar de manera mes neutre que fa el pr que ho pugui entendre una persona que no sap de que va.
- [ ] Si el canvi es visual, cal incloure un screenshot del abans i després (podeu enganxar una imatge a la descripció del github, es puja automticament)
- Quan feu commits, es important que la descripció sigui una mica mes entenedora (no posar "a" com a descripció). Sempre de la forma imperativa, com contestant a la pregunta: "If i apply this change it will ...", els 3 punts seria el que hauries d'escriure.

2020-11-26 10:43 UTC, IvanOrtizp commented
Perfecte, ara faig els canvis,
Gràcies.

El jue, 26 de nov. de 2020 a la(s) 11:38, Ivan Vergés (
notifications@github.com) escribió:

> *@microstudi* requested changes on this pull request.
>
> primer exemple de review (les reals son en anglès):
>
>    - Falta millorar la descripció del que has fet, no cal posar "I fix",
>    es millor posar de manera mes neutre que fa el pr que ho pugui entendre una
>    persona que no sap de que va.
>    - Si el canvi es visual, cal incloure un screenshot del abans i
>    després (podeu enganxar una imatge a la descripció del github, es puja
>    automticament)
>    - Quan feu commits, es important que la descripció sigui una mica mes
>    entenedora (no posar "a" com a descripció). Sempre de la forma imperativa,
>    com contestant a la pregunta: "If i apply this change it will ...", els 3
>    punts seria el que hauries d'escriure.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Platoniq/decidim/pull/33#pullrequestreview-539193549>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARJEF4YGJB2QONC6FQI35Y3SRYVZHANCNFSM4TULVB2A>
> .
>

2020-12-15 22:48 UTC, davidbeig commented on decidim-proposals/spec/shared/proposal_form_examples.rb
> -      # rubocop:disable RSpec/EmptyExampleGroup
This comments should not be deleted. Since this PR will be about decidim-debates, we should not change things in other components.

2020-12-15 22:48 UTC, davidbeig commented on decidim-proposals/spec/shared/proposal_form_examples.rb
> -      # rubocop:enable RSpec/EmptyExampleGroup
The same for this one

2020-12-15 22:48 UTC, davidbeig commented on decidim-core/app/assets/stylesheets/decidim/layouts/_view.scss
> +.icon-arrow-thin-right {
Do we want this class to be used in the whole of decidim or will it only be used in the cards used by debates? If so maybe it should go in another scss file related to cards or to debates.

2020-12-15 23:07 UTC, verarojman requested changes
Good work! I left some suggestions to improve the code and ensure it follows some standards that help us developers better understand each other :robot: 🌱 

Another thing that helps is to make sure your commit messages are descriptive (there are loooooots of guides of how to do it, I picked one randomly for you: https://chris.beams.io/posts/git-commit/#seven-rules)

![Commits](https://imgs.xkcd.com/comics/git_commit_2x.png)

2020-12-15 23:07 UTC, verarojman commented on decidim-debates/app/views/decidim/debates/debates/show.html.erb
> -
It is unnecessary to remove these blank lines, and it makes it more difficult to focus on the *real* changes this PR is making ;) The automatic `erb` linter should take care that .erb files have a concise style, you don't need to worry about it!

2020-12-15 23:07 UTC, verarojman commented on decidim-debates/app/views/decidim/debates/debates/show.html.erb
> +          <% if endorsements_enabled? && allowed_to?(:endorse, :debate, debate: debate) %>
Woops! Wrong indentation 🙆🏽‍♀️

2020-12-15 23:07 UTC, verarojman commented on decidim-debates/app/views/decidim/debates/debates/show.html.erb
> +            <% end %>
Nice! It's working as it should :) To improve it, I would:

- Run `erblint` to correct the indentation (check the decidim docs if you're not sure how to do it)
- Extracting the logic into a [Rails helper](https://www.rubyguides.com/2020/01/rails-helpers/) would be super super nice 👌🏽  That way this file would be more readable and therefore easy to understand.

2020-12-15 23:07 UTC, verarojman commented on decidim-debates/spec/system/multiple_date_spec.rb
> +    end
Good! You should add the other cases too (when only one day is displayed, when there is no end date...)

2020-12-17 09:02 UTC, IvanOrtizp commented
Thanks for the review

2021-07-21 13:44 UTC, closed without merging