Feature/show different days in debates
Platoniq/decidim pull request #39
Opened 2020-11-26 13:20 UTC by cf17jeremy

#### :tophat: What? Why?
*Adds multiple days (when starts on day and finish on other day) on debate (start day and finish day).*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #30 

#### Testing
*Going to some one debate who have multiple days*

#### :clipboard: Checklist
:rotating_light: Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] :question: **CONSIDER** adding a unit test if your PR resolves an issue.
- [x] :heavy_check_mark: **DO** check open PR's to avoid duplicates.
- [x] :heavy_check_mark: **DO** keep pull requests small so they can be easily reviewed.
- [x] :heavy_check_mark: **DO** build locally before pushing.
- [x] :heavy_check_mark: **DO** make sure tests pass.
- [x] :heavy_check_mark: **DO** make sure any new changes are documented in `docs/`.
- [x] :heavy_check_mark: **DO** add and modify seeds if necessary.
- [x] :heavy_check_mark: **DO** add CHANGELOG upgrade notes if required.
- [x] :heavy_check_mark: **DO** add to GraphQL API if there are new public fields.
- [x] :heavy_check_mark: **DO** add link to MetaDecidim if it's a new feature.
- [x] :x:**AVOID** breaking the continuous integration build.
- [x] :x:**AVOID** making significant changes to the overall architecture.

### :camera: Screenshots
**Before**
![before](https://user-images.githubusercontent.com/43346616/100351951-8ed45700-2fec-11eb-8127-eb040682768c.PNG)
**After**
![after](https://user-images.githubusercontent.com/43346616/100351983-998eec00-2fec-11eb-803f-7c3bbed13f1d.PNG)

:hearts: Thank you!

2020-12-15 22:22 UTC, davidbeig reviewed
This file has some lint problems. Could you solve them?

2020-12-15 23:35 UTC, verarojman requested changes
Good work! I left some suggestions to improve the code, it seems it's not quite finished yet 🤷🏽‍♀️ please tell me if you have any doubts about the comments I left, I hope they're useful!

I'll review again once you add some more specs ;)

2020-12-15 23:35 UTC, verarojman commented on decidim-debates/app/views/decidim/debates/debates/show.html.erb
> +  </div>
Nice! It's working as it should :) To improve it, I would:

- Run `erblint` to correct the indentation (check the decidim docs if you're not sure how to do it)
- Extracting the logic into a [Rails helper](https://www.rubyguides.com/2020/01/rails-helpers/) would be super super nice 👌🏽  That way this file would be more readable and therefore easy to understand.

2020-12-15 23:35 UTC, verarojman commented on decidim-debates/app/views/decidim/debates/debates/show.html.erb
> +      <div class="text-muted"><%= icon "arrow-thin-right" %></div>
You can pass classes to the icon helper, like this:
```suggestion
      <%= icon "arrow-thin-right", class: "text-muted" %>
```

2020-12-15 23:35 UTC, verarojman commented on decidim-debates/spec/system/debates_dates.rb
> +describe "Date comprober", versioning: true, type: :system do
"Date comprober" 🥇 👍🏽 Well, actually, it is a good practice for the name of the spec to match the file name!

```suggestion
describe "Debate dates", versioning: true, type: :system do
```

2020-12-15 23:35 UTC, verarojman commented on decidim-debates/spec/system/debates_dates.rb
> +    end
Where is this `Date` coming from?  😮  What is the output of this test?

Usually, in system specs for decidim (which uses Capybara), things are checked like this:

`expect(page).to have_content "foo bar"`

https://github.com/decidim/decidim/blob/release/0.23-stable/decidim-debates/spec/system/show_spec.rb

You should write specs for all the different cases: For different `start_time` and `end_time` combinations, check that the view has the content that you expect. More feedback coming when you do so! 🥳

2020-12-18 11:02 UTC, microstudi requested changes
Tests are failing @cf17jeremy:
![image](https://user-images.githubusercontent.com/1401520/102607580-ce441e00-4128-11eb-9abe-396ae5a1d52e.png)

On the other hand, look at the comments, there are some things to improve!

2020-12-18 11:02 UTC, microstudi commented on decidim-debates/spec/system/debates_dates_spec.rb
> +        expect(debate.start_time.strftime("%H")).to be < debate.end_time.strftime("%H")
You are check `debate` against `debate`? this kind of checks should be done in the model.
In here you need to check what's in the HTML view (the `page`). You might try to get the specific text for the element containing the displayed date

2020-12-18 11:02 UTC, microstudi commented on decidim-debates/app/views/decidim/debates/debates/show.html.erb
> +      </div>
Indentation is incorrect?

2021-07-21 13:44 UTC, closed without merging